import { DataTypes } from 'sequelize';

const uuidPk = {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
};

// ---------------------------------------------------------------------
// Enums (as reusable arrays for DataTypes.ENUM)
// ---------------------------------------------------------------------
const SUBJECT_TYPES = ['CORE', 'PROGRAM_ELECTIVE', 'OPEN_ELECTIVE'];
const ENROLLMENT_STATUSES = ['ENROLLED', 'PASSED', 'FAILED', 'WITHDRAWN'];
const ELECTIVE_CHOICE_STATUSES = ['PENDING', 'CONFIRMED', 'LOCKED', 'WITHDRAWN'];
const LEAVE_STATUSES = ['PENDING', 'APPROVED', 'REJECTED'];
const FEE_TYPES = ['FULL_SEMESTER', 'PER_SUBJECT'];
const PAYMENT_STATUSES = ['SUCCESS', 'FAILED', 'PENDING', 'REFUNDED'];
const EXAM_TYPES = ['MIDTERM', 'FINAL', 'INTERNAL', 'MAKEUP'];
const QUESTION_PAPER_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED'];
const ANNOUNCEMENT_TYPES = ['GLOBAL', 'DEPARTMENT', 'CLASS', 'DIVISION', 'TEACHER', 'PARENT'];
const SUBMISSION_STATUSES = ['UPLOAD', 'SUBMITTED', 'ACCEPTED'];
const COMPONENT_CATEGORIES = ['INTERNAL', 'EXTERNAL'];
const MARK_ENTRY_METHODS = ['MANUAL', 'ONLINE_TEST', 'FORMAL_EXAM'];



export { uuidPk, SUBJECT_TYPES, ENROLLMENT_STATUSES, ELECTIVE_CHOICE_STATUSES, LEAVE_STATUSES, FEE_TYPES, PAYMENT_STATUSES, EXAM_TYPES, QUESTION_PAPER_STATUSES, ANNOUNCEMENT_TYPES, SUBMISSION_STATUSES, COMPONENT_CATEGORIES, MARK_ENTRY_METHODS };
